TOP_DIRECTORY=../../..
SUB_DIRECTORIES=test
LIBRARY=extraffic_packet
SOURCES= \
	Packet.cpp \
	EtherHeader.cpp \
	IpHeader.cpp \
	UdpHeader.cpp \
	TcpHeader.cpp \

-include $(TOP_DIRECTORY)/mk/library.mk
-include $(TOP_DIRECTORY)/mk/subdirectory.mk

